### ISSUE TITLE
Inconsistent dependencies prevent installation

### ISSUE THREAD

**Issue by jschirrmacher** [piniajs/example-vue-2-vite#37]
When I clone the current repository and call `npm install`, I get the following messages:

```
➜  example-vue-2-vite git:(main) npm i                     
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: pinia-vue-2@0.0.0
npm ERR! Found: vue@2.7.0-beta.3
npm ERR! node_modules/vue
npm ERR!   vue@"^2.7.0-beta.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^2.6.14 || ^3.2.0" from pinia@2.0.14
npm ERR! node_modules/pinia
npm ERR!   pinia@"^2.0.14" from the root project
```

**Comment by posva** [comment]
override it with `vue@2` at the moment. I shouldn't have pushed the tests to the main branch

**Comment by posva** [comment]
But pnpm handles it well, weird.

**Comment by jschirrmacher** [comment]
When using `npm i vue@2`, I get
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: pinia-vue-2@0.0.0
npm ERR! Found: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   vue@"2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer vue@"^2.7.0-0" from @vitejs/plugin-vue2@1.1.0
npm ERR! node_modules/@vitejs/plugin-vue2
npm ERR!   dev @vitejs/plugin-vue2@"^1.1.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

while `npm i vue@2 --legacy-peer-deps` seem to work

**Comment by jschirrmacher** [comment]
However, `npm run dev` reports
```
➜  example-vue-2-vite git:(main) ✗ npm run dev

> pinia-vue-2@0.0.0 dev
> vite

error when starting dev server:
Error: Failed to resolve vue/compiler-sfc.
@vitejs/plugin-vue2 requires vue (>=2.7.0) to be present in the dependency tree.
```

**Comment by posva** [comment]
yeah, that also needs to be changed. You can refer to https://github.com/piniajs/example-vue-2-vite/commit/c4e16bbef2071ca6da1e1576dc872a5ec10a6f87 to see a version working with vue 2. However, if you want to use this to scaffold a new project, you should use Vue 3 instead 😄 
Good luck!

**Comment by jschirrmacher** [comment]
Thanks for your quick responses! I'll try https://github.com/piniajs/example-vue-2-vite/commit/c4e16bbef2071ca6da1e1576dc872a5ec10a6f87 then.

In fact, I try to use the package to check why my (larger) vue2 project doesn't work with pinia (I get the same problems there), so it seems I have to stick with vue2 for now or need to migrate to vue3 first. 😞

**Comment by jschirrmacher** [comment]
The commit you mentioned seems to be the current `main` HEAD. This was the first version I used, so this doesn't seem to work.

**Comment by Morl99** [comment]
We finally found the problem, we are using ignore-scripts=true in all our setups (as a security measure), and vue-demi has a post install script to determine the vue version. This script never ran, so the code did not behave as expected. It works now, thank you for your help!
